live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#686868"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#eff0eb"
yellow = "#f3f99d"

[colors.cursor]
cursor = "#97979b"

[colors.normal]
black = "#282a36"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#f1f1f0"
yellow = "#f3f99d"

[colors.primary]
background = "#282a36"
foreground = "#eff0eb"

[colors.selection]
background = "#feffff"
text = "#282a36"

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "Source Code Pro for Powerline"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro for Powerline"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 7

[font.italic]
family = "Source Code Pro for Powerline"
style = "Italic"

[font.normal]
family = "Source Code Pro for Powerline"
style = "Regular"

[font.offset]
x = 0
y = 14

[[keyboard.bindings]]
chars = '\p'
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = '\n'
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/opt/homebrew/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 151
lines = 15

[window.position]
x = 0
y = 0
